name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  core:
      path: ../core
  angular: ^5.0.0
  key_value_store_web: ^1.0.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+19
  pwa: ^0.1.11

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
